name: E2E Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: ./mvnw -B clean package -Dmaven.test.skip=true --file pom.xml

      - name: Cache Docker images
        uses: ScribeMD/docker-cache@fb28c93772363301b8d0a6072ce850224b73f74e
        with:
          key: docker-cache-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Run E2E Tests with Docker Compose
        run: docker compose -f docker-compose-e2e.yml up --build --abort-on-container-exit --exit-code-from e2e-tests

      - name: Tear down Docker Compose
        if: always()
        run: docker compose -f docker-compose-e2e.yml down -v --rmi local

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 7
      - uses: daun/playwright-report-summary@8bb85779022480a59ed8d33d9a4b8bda1c67666b
        if: always()
        with:
          report-file: e2e/test-results/results.json
